//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ban
    {
        public int BanID { get; set; }
        public Nullable<int> KhuVucID { get; set; }
        public string TenBan { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
