//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int ChiTietHoaDonID { get; set; }
        public Nullable<int> MatHangID { get; set; }
        public Nullable<System.Guid> HoaDonID { get; set; }
        public Nullable<int> KhuyenMaiID { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<int> PhanTramKM { get; set; }
    }
}
