//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucNang_NhomQuyen
    {
        public int NhomQuyenID { get; set; }
        public int ChucNangID { get; set; }
        public Nullable<int> Xem { get; set; }
        public Nullable<int> Them { get; set; }
        public Nullable<int> Sua { get; set; }
        public Nullable<int> Xoa { get; set; }
    }
}
