//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public System.Guid HoaDonID { get; set; }
        public Nullable<int> BanID { get; set; }
        public Nullable<int> NguoiDungID { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> DaThanhToan { get; set; }
        public Nullable<double> GiamTien { get; set; }
        public Nullable<double> ThanhToan { get; set; }
        public Nullable<int> HuyBan { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    }
}
