//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        public int MatHangID { get; set; }
        public Nullable<int> LoaiHangID { get; set; }
        public string TenMatHang { get; set; }
        public Nullable<double> Gia { get; set; }
        public string FileAnh { get; set; }
    }
}
