//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public int NguoiDungID { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string CMND { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> NhomQuyenID { get; set; }
        public string AnhDaiDien { get; set; }
    }
}
