//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomQuyen
    {
        public int NhomQuyenID { get; set; }
        public string TenNhomQuyen { get; set; }
        public string NoiDung { get; set; }
    }
}
